// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL_DIRECT (plain postgres://) for migrations so they can
    // reach the Docker container directly, bypassing any proxy/Accelerate URL.
    url: process.env["DATABASE_URL_DIRECT"] ?? process.env["DATABASE_URL"],
  },
});
